version: "3.9"
services:
    publicapi:
        build: /api-app
        image: python-api-app
        ports:
            - "8000:8000"
        networks:
            - main
    processor:
        build: /processor-app
        image: python-processor-app
        ports:
            - "6379:6379"
        networks:
            - main
networks:
    main: