version: "3.9"
services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: unless-stopped
        command: mongod --auth
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 1234
            MONGO_INITDB_DATABASE: currencies_db
            MONGODB_DATA_DIR: /data/db
            MONDODB_LOG_DIR: /dev/null
        volumes:
            - mongodbdata:/data/db
        ports:
            - 27017:27017
        networks:
            - app-tier

    zookeeper:
        container_name: zookeeper
        image: bitnami/zookeeper:latest
        build:
            context: ./
            dockerfile: ./kafka/zookeeper/Dockerfile
        environment:
            - ZOOKEEPER_CLIENT_PORT=2181
        volumes:
            - ./kafka/config/zookeeper.properties:/kafka/config/zookeeper.properties
            - ~/kafka/data/zookeeper_log:/var/lib/zookeeper/log
        ports:
            - "2181:2181"
        networks:
            - app-tier

    kafka:
        container_name: kafka
        image: bitnami/kafka:latest
        build:
            context: ./
            dockerfile: ./kafka/Dockerfile
        volumes:
            - ./kafka/config/server.properties:/kafka/config/server.properties
        ports:
            - "9092:9092"
        networks:
            - app-tier
        depends_on:
            - zookeeper

    publicapi:
        container_name: publicapi
        build:
            context: ./
            dockerfile: ./api-app/Dockerfile
        image: python-api-app
        ports:
            - "8000:8000"
        networks:
            - app-tier

    processor:
        container_name: processor
        build:
            context: ./
            dockerfile: ./processor-app/Dockerfile
        image: python-processor-app
        ports:
            - "6379:6379"
        networks:
            - app-tier
        depends_on:
            - publicapi
            - mongodb

    alerts:
        container_name: alerts
        build:
            context: ./
            dockerfile: ./alerts-app/Dockerfile
        image: python-alerts-app
        ports:
            - "6165:6165"
        networks:
            - app-tier
        depends_on:
            - mongodb
            - zookeeper
            - kafka
        restart: on-failure
        
networks:
    app-tier:
      driver: bridge

volumes:
    mongodbdata:
        external: false

