version: "3.9"
services:
    publicapi:
        container_name: publicapi
        build:
            context: ./
            dockerfile: ./api-app/Dockerfile
        image: python-api-app
        ports:
            - "8000:8000"
        networks:
            - main
    processor:
        container_name: processor
        build:
            context: ./
            dockerfile: ./processor-app/Dockerfile
        image: python-processor-app
        ports:
            - "6379:6379"
        networks:
            - main
    alerts:
        container_name: alerts
        build:
            context: ./
            dockerfile: ./alerts-app/Dockerfile
        image: python-alerts-app
        ports:
            - "6165:6165"
        networks:
            - main
    # zookeeper:
    #     container_name: zookeeper
    #     image: zookeeper
    #     build:
    #         context: ./zookeeper
    #     volumes:
    #         - ./config/zookeeper.properties:/kafka/config/zookeeper.properties
    # kafka:
    #     container_name: kafka
    #     image: bitnami/kafka
    #     build: 
    #         context: .
    #     volumes:
    #         - ./config/server.properties:/kafka/config/server.properties
    #         - ./data/kafka/:/tmp/kafka-logs/
    # kafka-producer:
    #     container_name: kafka-producer
    #     image: bitnami/kafka
    #     build: 
    #         context: .
    #     working_dir: /kafka
    #     entrypoint: /bin/bash
    #     stdin_open: true
    #     tty: true
    # kafka-consumer:
    #     container_name: kafka-consumer
    #     image: bitnami/kafka
    #     build: 
    #         context: .
    #     working_dir: /kafka
    #     entrypoint: /bin/bash
    #     stdin_open: true
    #     tty: true

    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: unless-stopped
        command: mongod --auth
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 1234
            MONGO_INITDB_DATABASE: currencies_db
            MONGODB_DATA_DIR: /data/db
            MONDODB_LOG_DIR: /dev/null
        volumes:
            - mongodbdata:/data/db
        ports:
            - 27017:27017
        networks:
            - main
networks:
    main:
        driver: bridge
volumes:
    mongodbdata:
        external: false

